package pyqt5.qtwidgets;

import pyqt5.qtwidgets.QAbstractItemView;
import pyqt5.qtwidgets.QWidget;
import pyqt5.qtcore.QAbstractItemModel;
import pyqt5.qtcore.QItemSelectionModel;
import pyqt5.qtwidgets.QHeaderView;
import pyqt5.qtcore.QString;
import pyqt5.qtcore.QRect;
import pyqt5.qtcore.QPoint;
import pyqt5.qtcore.QSignal;
import pyqt5.qtcore.QVector;
import pyqt5.qtcore.Qt;
import pyqt5.qtgui.QRegion;
import pyqt5.qtgui.QInputEvent;
import pyqt5.qtcore.QEvent;
import pyqt5.qtgui.QPainter;
import pyqt5.qtwidgets.QStyleOption;
import pyqt5.qtcore.QSize;

@:pythonImport("PyQt5.QtWidgets", "QTreeView")
@:native("QTreeView")
extern class QTreeView extends QAbstractItemView {
	var expanded:QSignal1<QModelIndex>;
	var collapsed:QSignal1<QModelIndex>;

	function new(?parent:QWidget);

	function setModel(model:QAbstractItemModel):Void;
	function setRootIndex(index:QModelIndex):Void;
	function setSelectionModel(selectionModel:QItemSelectionModel):Void;
	function header():QHeaderView;
	function setHeader(header:QHeaderView):Void;
	function indentation():Int;
	function setIndentation(i:Int):Void;
	function rootIsDecorated():Bool;
	function setRootIsDecorated(show:Bool):Void;
	function uniformRowHeights():Bool;
	function setUniformRowHeights(uniform:Bool):Void;
	function itemsExpandable():Bool;
	function setItemsExpandable(enable:Bool):Void;
	function columnViewportPosition(column:Int):Int;
	function columnWidth(column:Int):Int;
	function columnAt(x:Int):Int;
	function isColumnHidden(column:Int):Bool;
	function setColumnHidden(column:Int, hide:Bool):Void;
	function isRowHidden(row:Int, parent:QModelIndex):Bool;
	function setRowHidden(row:Int, parent:QModelIndex, hide:Bool):Void;
	function isExpanded(index:QModelIndex):Bool;
	function setExpanded(index:QModelIndex, expand:Bool):Void;
	function keyboardSearch(search:QString):Void;
	function visualRect(index:QModelIndex):QRect;
	function scrollTo(index:QModelIndex, ?hint:QAbstractItemViewScrollHint):Void;
	function indexAt(p:QPoint):QModelIndex;
	function indexAbove(index:QModelIndex):QModelIndex;
	function indexBelow(index:QModelIndex):QModelIndex;
	function reset():Void;
	function dataChanged(topLeft:QModelIndex, bottomRight:QModelIndex, ?roles:QVector<Int>):Void;
	function hideColumn(column:Int):Void;
	function showColumn(column:Int):Void;
	function expand(index:QModelIndex):Void;
	function expandAll():Void;
	function collapse(index:QModelIndex):Void;
	function collapseAll():Void;
	function resizeColumnToContents(column:Int):Void;
	function selectAll():Void;
	function columnResized(column:Int, oldSize:Int, newSize:Int):Void;
	function columnCountChanged(oldCount:Int, newCount:Int):Void;
	function columnMoved():Void;
	function reexpand():Void;
	function rowsRemoved(parent:QModelIndex, first:Int, last:Int):Void;
	function scrollContentsBy(dx:Int, dy:Int):Void;
	function rowsInserted(parent:QModelIndex, start:Int, end:Int):Void;
	function rowsAboutToBeRemoved(parent:QModelIndex, start:Int, end:Int):Void;
	function moveCursor(cursorAction:QAbstractItemViewCursorAction, modifiers:QtKeyboardModifiers):QModelIndex;
	function horizontalOffset():Int;
	function verticalOffset():Int;
	function setSelection(rect:QRect, command:QItemSelectionModelSelectionFlags):Void;
	function visualRegionForSelection(selection:QItemSelection):QRegion;
	function selectedIndexes():QModelIndexList;
	function paintEvent(e:QPaintEvent):Void;
	function timerEvent(event:QTimerEvent):Void;
	function mouseReleaseEvent(event:QMouseEvent):Void;
	function drawRow(painter:QPainter, options:QStyleOptionViewItem, index:QModelIndex):Void;
	function drawBranches(painter:QPainter, rect:QRect, index:QModelIndex):Void;
	function drawTree(painter:QPainter, region:QRegion):Void;
	function mousePressEvent(e:QMouseEvent):Void;
	function mouseMoveEvent(event:QMouseEvent):Void;
	function mouseDoubleClickEvent(e:QMouseEvent):Void;
	function keyPressEvent(event:QKeyEvent):Void;
	function updateGeometries():Void;
	function sizeHintForColumn(column:Int):Int;
	function indexRowSizeHint(index:QModelIndex):Int;
	function horizontalScrollbarAction(action:Int):Void;
	function isIndexHidden(index:QModelIndex):Bool;
	function setColumnWidth(column:Int, width:Int):Void;
	function setSortingEnabled(enable:Bool):Void;
	function isSortingEnabled():Bool;
	function setAnimated(enable:Bool):Void;
	function isAnimated():Bool;
	function setAllColumnsShowFocus(enable:Bool):Void;
	function allColumnsShowFocus():Bool;
	function sortByColumn(column:Int, order:QtSortOrder):Void;
	function autoExpandDelay():Int;
	function setAutoExpandDelay(delay:Int):Void;
	function isFirstColumnSpanned(row:Int, parent:QModelIndex):Bool;
	function setFirstColumnSpanned(row:Int, parent:QModelIndex, span:Bool):Void;
	function setWordWrap(on:Bool):Void;
	function wordWrap():Bool;
	function expandToDepth(depth:Int):Void;
	function dragMoveEvent(event:QDragMoveEvent):Void;
	function viewportEvent(event:QEvent):Bool;
	function rowHeight(index:QModelIndex):Int;
	function selectionChanged(selected:QItemSelection, deselected:QItemSelection):Void;
	function currentChanged(current:QModelIndex, previous:QModelIndex):Void;
	function expandsOnDoubleClick():Bool;
	function setExpandsOnDoubleClick(enable:Bool):Void;
	function isHeaderHidden():Bool;
	function setHeaderHidden(hide:Bool):Void;
	function setTreePosition(logicalIndex:Int):Void;
	function treePosition():Int;
	function viewportSizeHint():QSize;
	function resetIndentation():Void;
	function expandRecursively(index:QModelIndex, ?depth:Int):Void;
}

